const APPS = [
  {
    "name": "Biblioteca-de-Sue-os",
    "description": "PWA offline para registrar sueños, analizarlos simbólicamente, detectar patrones, visualizar una constelación de símbolos y estudiar una línea temporal.",
    "language": "JavaScript",
    "license": "MIT",
    "updated": "Hace 3 días",
    "category": "Escritura / Vida",
    "github": "https://github.com/ivan7800/Biblioteca-de-Sue-os",
    "pages": "https://ivan7800.github.io/Biblioteca-de-Sue-os/",
    "slug": "biblioteca-de-sue-os",
    "icon": "⌘",
    "saga": "Archivo simbólico",
    "coverTone": "noir",
    "coverTitle": "Biblioteca de Sue os",
    "short": "PWA offline para registrar sueños, analizarlos simbólicamente, detectar patrones, visualizar una constelación de símbolo…",
    "screenshot": "assets/screenshots/Biblioteca-de-Sue-os.svg"
  },
  {
    "name": "Biblioteca-Oculta",
    "description": "PWA esotérica offline-first en HTML, CSS y JavaScript puro.",
    "language": "JavaScript",
    "license": "Other",
    "updated": "Hace 2 días",
    "category": "Esoterismo / Ficción",
    "github": "https://github.com/ivan7800/Biblioteca-Oculta",
    "pages": "https://ivan7800.github.io/Biblioteca-Oculta/",
    "slug": "biblioteca-oculta",
    "icon": "✦",
    "saga": "Archivo simbólico",
    "coverTone": "cosmic",
    "coverTitle": "Biblioteca Oculta",
    "short": "PWA esotérica offline-first en HTML, CSS y JavaScript puro.",
    "screenshot": "assets/screenshots/Biblioteca-Oculta.svg"
  },
  {
    "name": "I-Ching",
    "description": "App web offline inspirada en el I Ching.",
    "language": "JavaScript",
    "license": "MIT",
    "updated": "Hace 3 días",
    "category": "Esoterismo / Ficción",
    "github": "https://github.com/ivan7800/I-Ching",
    "pages": "https://ivan7800.github.io/I-Ching/",
    "slug": "i-ching",
    "icon": "✦",
    "saga": "Archivo simbólico",
    "coverTone": "violet",
    "coverTitle": "I Ching",
    "short": "App web offline inspirada en el I Ching.",
    "screenshot": "assets/screenshots/I-Ching.svg"
  },
  {
    "name": "Ouija",
    "description": "Experiencia interactiva de ficción inspirada en tablas ouija clásicas.",
    "language": "JavaScript",
    "license": "MIT",
    "updated": "Hace 3 días",
    "category": "Esoterismo / Ficción",
    "github": "https://github.com/ivan7800/Ouija",
    "pages": "https://ivan7800.github.io/Ouija/",
    "slug": "ouija",
    "icon": "✦",
    "saga": "Archivo simbólico",
    "coverTone": "violet",
    "coverTitle": "Ouija",
    "short": "Experiencia interactiva de ficción inspirada en tablas ouija clásicas.",
    "screenshot": "assets/screenshots/Ouija.svg"
  },
  {
    "name": "Tarot",
    "description": "App web local y offline de tarot, pensada para abrirse directamente en navegador.",
    "language": "JavaScript",
    "license": "MIT",
    "updated": "Hace 3 días",
    "category": "Esoterismo / Ficción",
    "github": "https://github.com/ivan7800/Tarot",
    "pages": "https://ivan7800.github.io/Tarot/",
    "slug": "tarot",
    "icon": "✦",
    "saga": "Archivo simbólico",
    "coverTone": "cyan",
    "coverTitle": "Tarot",
    "short": "App web local y offline de tarot, pensada para abrirse directamente en navegador.",
    "screenshot": "assets/screenshots/Tarot.svg"
  },
  {
    "name": "Atlas-Web-Pro",
    "description": "Directorio local de herramientas web para IA, productividad, libros, cursos, programación, diseño, vídeo/audio, escritura, ciencia y seguridad.",
    "language": "JavaScript",
    "license": "Other",
    "updated": "Hace 4 días",
    "category": "Productividad / Directorios",
    "github": "https://github.com/ivan7800/Atlas-Web-Pro",
    "pages": "https://ivan7800.github.io/Atlas-Web-Pro/",
    "slug": "atlas-web-pro",
    "icon": "◆",
    "saga": "Estudio audiovisual",
    "coverTone": "paper",
    "coverTitle": "Atlas Web Pro",
    "short": "Directorio local de herramientas web para IA, productividad, libros, cursos, programación, diseño, vídeo/audio, escritur…",
    "screenshot": "assets/screenshots/Atlas-Web-Pro.svg"
  },
  {
    "name": "fotocinema",
    "description": "Estudio web offline para crear pases de recuerdos con fotos, vídeos, títulos, música, transiciones, skins visuales y exportaciones portables.",
    "language": "JavaScript",
    "license": "MIT",
    "updated": "Hace 2 días",
    "category": "Visual / Foto",
    "github": "https://github.com/ivan7800/fotocinema",
    "pages": "https://ivan7800.github.io/fotocinema/",
    "slug": "fotocinema",
    "icon": "▣",
    "saga": "Estudio audiovisual",
    "coverTone": "violet",
    "coverTitle": "fotocinema",
    "short": "Estudio web offline para crear pases de recuerdos con fotos, vídeos, títulos, música, transiciones, skins visuales y exp…",
    "screenshot": "assets/screenshots/fotocinema.svg"
  },
  {
    "name": "FotoLibro-Studio-Pro",
    "description": "Editor offline de fotolibros para navegador con interfaz editorial, presets premium, drag & drop, guardado local y revisión.",
    "language": "JavaScript",
    "license": "MIT",
    "updated": "Hace 2 días",
    "category": "Visual / Foto",
    "github": "https://github.com/ivan7800/FotoLibro-Studio-Pro",
    "pages": "https://ivan7800.github.io/FotoLibro-Studio-Pro/",
    "slug": "fotolibro-studio-pro",
    "icon": "▣",
    "saga": "Estudio audiovisual",
    "coverTone": "noir",
    "coverTitle": "FotoLibro Studio Pro",
    "short": "Editor offline de fotolibros para navegador con interfaz editorial, presets premium, drag & drop, guardado local y revis…",
    "screenshot": "assets/screenshots/FotoLibro-Studio-Pro.svg"
  },
  {
    "name": "INSANITY",
    "description": "Sintetizador de audio oscuro de un único archivo HTML.",
    "language": "HTML",
    "license": "MIT",
    "updated": "Hace 2 semanas",
    "category": "Música / Audio",
    "github": "https://github.com/ivan7800/INSANITY",
    "pages": "https://ivan7800.github.io/INSANITY/",
    "slug": "insanity",
    "icon": "♪",
    "saga": "Estudio audiovisual",
    "coverTone": "signal",
    "coverTitle": "INSANITY",
    "short": "Sintetizador de audio oscuro de un único archivo HTML.",
    "screenshot": "assets/screenshots/INSANITY.svg"
  },
  {
    "name": "musica-404",
    "description": "Secuenciador musical web inspirado en Music 2000 de PSX.",
    "language": "JavaScript",
    "license": "MIT",
    "updated": "Hace 4 días",
    "category": "Música / Audio",
    "github": "https://github.com/ivan7800/musica-404",
    "pages": "https://ivan7800.github.io/musica-404/",
    "slug": "musica-404",
    "icon": "♪",
    "saga": "Estudio audiovisual",
    "coverTone": "paper",
    "coverTitle": "musica 404",
    "short": "Secuenciador musical web inspirado en Music 2000 de PSX.",
    "screenshot": "assets/screenshots/musica-404.svg"
  },
  {
    "name": "Nocturne",
    "description": "Arquitectura sonora procedural para escritores, narradores y worldbuilders.",
    "language": "JavaScript",
    "license": "MIT",
    "updated": "Hace 2 días",
    "category": "Música / Escritura",
    "github": "https://github.com/ivan7800/Nocturne",
    "pages": "https://ivan7800.github.io/Nocturne/",
    "slug": "nocturne",
    "icon": "♪",
    "saga": "Estudio audiovisual",
    "coverTone": "violet",
    "coverTitle": "Nocturne",
    "short": "Arquitectura sonora procedural para escritores, narradores y worldbuilders.",
    "screenshot": "assets/screenshots/Nocturne.svg"
  },
  {
    "name": "Photo-Studio-OS",
    "description": "AI Photography Director Suite.",
    "language": "JavaScript",
    "license": "Sin especificar",
    "updated": "Hace 3 días",
    "category": "Visual / Foto",
    "github": "https://github.com/ivan7800/Photo-Studio-OS",
    "pages": "https://ivan7800.github.io/Photo-Studio-OS/",
    "slug": "photo-studio-os",
    "icon": "▣",
    "saga": "Estudio audiovisual",
    "coverTone": "cyan",
    "coverTitle": "Photo Studio OS",
    "short": "AI Photography Director Suite.",
    "screenshot": "assets/screenshots/Photo-Studio-OS.svg"
  },
  {
    "name": "PocketTone-Archive",
    "description": "Museo jugable en navegador de once teclados de bolsillo imaginarios de 1980 a 1991.",
    "language": "JavaScript",
    "license": "Other",
    "updated": "Hace 3 días",
    "category": "Música / Audio",
    "github": "https://github.com/ivan7800/PocketTone-Archive",
    "pages": "https://ivan7800.github.io/PocketTone-Archive/",
    "slug": "pockettone-archive",
    "icon": "♪",
    "saga": "Estudio audiovisual",
    "coverTone": "cosmic",
    "coverTitle": "PocketTone Archive",
    "short": "Museo jugable en navegador de once teclados de bolsillo imaginarios de 1980 a 1991.",
    "screenshot": "assets/screenshots/PocketTone-Archive.svg"
  },
  {
    "name": "Storyboard-Studio",
    "description": "Crea un storyboard de tu manuscrito.",
    "language": "HTML",
    "license": "Other",
    "updated": "Hace 4 días",
    "category": "Escritura / Visual",
    "github": "https://github.com/ivan7800/Storyboard-Studio",
    "pages": "https://ivan7800.github.io/Storyboard-Studio/",
    "slug": "storyboard-studio",
    "icon": "⌘",
    "saga": "Estudio audiovisual",
    "coverTone": "signal",
    "coverTitle": "Storyboard Studio",
    "short": "Crea un storyboard de tu manuscrito.",
    "screenshot": "assets/screenshots/Storyboard-Studio.svg"
  },
  {
    "name": "AETHERION-Editorial-OS",
    "description": "Aplicación local-first para escritores y editores que quieren auditar una novela con rigor.",
    "language": "JavaScript",
    "license": "MIT",
    "updated": "Hace 3 días",
    "category": "Escritura / IA",
    "github": "https://github.com/ivan7800/AETHERION-Editorial-OS",
    "pages": "https://ivan7800.github.io/AETHERION-Editorial-OS/",
    "slug": "aetherion-editorial-os",
    "icon": "⌘",
    "saga": "Formación & IT",
    "coverTone": "cyan",
    "coverTitle": "AETHERION Editorial OS",
    "short": "Aplicación local-first para escritores y editores que quieren auditar una novela con rigor.",
    "screenshot": "assets/screenshots/AETHERION-Editorial-OS.svg"
  },
  {
    "name": "Ajedrez-Maestro",
    "description": "App web de ajedrez offline-first, preparada para GitHub Pages y uso como PWA.",
    "language": "JavaScript",
    "license": "Sin especificar",
    "updated": "Hace 4 horas",
    "category": "Juegos / Formación",
    "github": "https://github.com/ivan7800/Ajedrez-Maestro",
    "pages": "https://ivan7800.github.io/Ajedrez-Maestro/",
    "slug": "ajedrez-maestro",
    "icon": "♞",
    "saga": "Formación & IT",
    "coverTone": "violet",
    "coverTitle": "Ajedrez Maestro",
    "short": "App web de ajedrez offline-first, preparada para GitHub Pages y uso como PWA.",
    "screenshot": "assets/screenshots/Ajedrez-Maestro.svg"
  },
  {
    "name": "Atlas-Librorum",
    "description": "App web local para convertir fuentes de libros digitales en buscador, biblioteca personal, cuaderno de escritor y archivo de citas.",
    "language": "JavaScript",
    "license": "Other",
    "updated": "Hace 3 días",
    "category": "Libros / Escritura",
    "github": "https://github.com/ivan7800/Atlas-Librorum",
    "pages": "https://ivan7800.github.io/Atlas-Librorum/",
    "slug": "atlas-librorum",
    "icon": "⌘",
    "saga": "Formación & IT",
    "coverTone": "noir",
    "coverTitle": "Atlas Librorum",
    "short": "App web local para convertir fuentes de libros digitales en buscador, biblioteca personal, cuaderno de escritor y archiv…",
    "screenshot": "assets/screenshots/Atlas-Librorum.svg"
  },
  {
    "name": "Cauers4ever",
    "description": "Suite profesional de soporte técnico para Windows 10/11 y PowerShell 5.1+.",
    "language": "PowerShell",
    "license": "Other",
    "updated": "Hace 3 días",
    "category": "Windows / IT",
    "github": "https://github.com/ivan7800/Cauers4ever",
    "pages": "https://ivan7800.github.io/Cauers4ever/",
    "slug": "cauers4ever",
    "icon": "⌘",
    "saga": "Formación & IT",
    "coverTone": "violet",
    "coverTitle": "Cauers4ever",
    "short": "Suite profesional de soporte técnico para Windows 10/11 y PowerShell 5.1+.",
    "screenshot": "assets/screenshots/Cauers4ever.svg"
  },
  {
    "name": "diario-moleskine",
    "description": "Diario local para el día a día.",
    "language": "HTML",
    "license": "MIT",
    "updated": "Hace 3 días",
    "category": "Escritura / Vida",
    "github": "https://github.com/ivan7800/diario-moleskine",
    "pages": "https://ivan7800.github.io/diario-moleskine/",
    "slug": "diario-moleskine",
    "icon": "⌘",
    "saga": "Formación & IT",
    "coverTone": "signal",
    "coverTitle": "diario moleskine",
    "short": "Diario local para el día a día.",
    "screenshot": "assets/screenshots/diario-moleskine.svg"
  },
  {
    "name": "json404",
    "description": "Aplicación web estática para abrir, entender, auditar, limpiar y convertir archivos .json sin subirlos a internet.",
    "language": "HTML",
    "license": "MIT",
    "updated": "Hace 2 días",
    "category": "Datos / Dev",
    "github": "https://github.com/ivan7800/json404",
    "pages": "https://ivan7800.github.io/json404/",
    "slug": "json404",
    "icon": "{ }",
    "saga": "Formación & IT",
    "coverTone": "cyan",
    "coverTitle": "json404",
    "short": "Aplicación web estática para abrir, entender, auditar, limpiar y convertir archivos .json sin subirlos a internet.",
    "screenshot": "assets/screenshots/json404.svg"
  },
  {
    "name": "NetLab-404",
    "description": "Entrenador CCNA offline-first listo para GitHub Pages con ruta de estudio, preguntas, examen, subnetting, terminal Cisco educativa y labs.",
    "language": "JavaScript",
    "license": "MIT",
    "updated": "Hace 4 horas",
    "category": "Formación / IT",
    "github": "https://github.com/ivan7800/NetLab-404",
    "pages": "https://ivan7800.github.io/NetLab-404/",
    "slug": "netlab-404",
    "icon": "⌘",
    "saga": "Formación & IT",
    "coverTone": "cyan",
    "coverTitle": "NetLab 404",
    "short": "Entrenador CCNA offline-first listo para GitHub Pages con ruta de estudio, preguntas, examen, subnetting, terminal Cisco…",
    "screenshot": "assets/screenshots/NetLab-404.svg"
  },
  {
    "name": "os404",
    "description": "Sistema operativo simulado en una app web HTML/CSS/JS, preparado para GitHub Pages.",
    "language": "JavaScript",
    "license": "MIT",
    "updated": "Hace 5 horas",
    "category": "Sistema / Experimentos",
    "github": "https://github.com/ivan7800/os404",
    "pages": "https://ivan7800.github.io/os404/",
    "slug": "os404",
    "icon": "◆",
    "saga": "Formación & IT",
    "coverTone": "noir",
    "coverTitle": "os404",
    "short": "Sistema operativo simulado en una app web HTML/CSS/JS, preparado para GitHub Pages.",
    "screenshot": "assets/screenshots/os404.svg"
  },
  {
    "name": "portal-descargas-corporativas",
    "description": "Portal web estático para acceso directo a descargas oficiales de aplicaciones aprobadas por IT.",
    "language": "HTML",
    "license": "MIT",
    "updated": "Hace 2 semanas",
    "category": "Windows / IT",
    "github": "https://github.com/ivan7800/portal-descargas-corporativas",
    "pages": "https://ivan7800.github.io/portal-descargas-corporativas/",
    "slug": "portal-descargas-corporativas",
    "icon": "⌘",
    "saga": "Formación & IT",
    "coverTone": "cosmic",
    "coverTitle": "portal descargas corporativas",
    "short": "Portal web estático para acceso directo a descargas oficiales de aplicaciones aprobadas por IT.",
    "screenshot": "assets/screenshots/portal-descargas-corporativas.svg"
  },
  {
    "name": "recetario",
    "description": "Aplicación web local, instalable y preparada para GitHub Pages para guardar recetas, organizar ingredientes, planificar menús y generar listas de compra.",
    "language": "HTML",
    "license": "Sin especificar",
    "updated": "Hace 3 días",
    "category": "Vida / Utilidad",
    "github": "https://github.com/ivan7800/recetario",
    "pages": "https://ivan7800.github.io/recetario/",
    "slug": "recetario",
    "icon": "◆",
    "saga": "Formación & IT",
    "coverTone": "noir",
    "coverTitle": "recetario",
    "short": "Aplicación web local, instalable y preparada para GitHub Pages para guardar recetas, organizar ingredientes, planificar…",
    "screenshot": "assets/screenshots/recetario.svg"
  },
  {
    "name": "SafeSignal",
    "description": "PWA estática de asistencia rápida, discreta y privada para situaciones de riesgo.",
    "language": "JavaScript",
    "license": "MIT",
    "updated": "Hace 4 días",
    "category": "Seguridad / Vida",
    "github": "https://github.com/ivan7800/SafeSignal",
    "pages": "https://ivan7800.github.io/SafeSignal/",
    "slug": "safesignal",
    "icon": "●",
    "saga": "Formación & IT",
    "coverTone": "paper",
    "coverTitle": "SafeSignal",
    "short": "PWA estática de asistencia rápida, discreta y privada para situaciones de riesgo.",
    "screenshot": "assets/screenshots/SafeSignal.svg"
  },
  {
    "name": "sin-bruma",
    "description": "App para ayudar a dejar malos hábitos.",
    "language": "HTML",
    "license": "MIT",
    "updated": "Hace 3 días",
    "category": "Bienestar / Vida",
    "github": "https://github.com/ivan7800/sin-bruma",
    "pages": "https://ivan7800.github.io/sin-bruma/",
    "slug": "sin-bruma",
    "icon": "●",
    "saga": "Formación & IT",
    "coverTone": "paper",
    "coverTitle": "sin bruma",
    "short": "App para ayudar a dejar malos hábitos.",
    "screenshot": "assets/screenshots/sin-bruma.svg"
  },
  {
    "name": "Windows-Master-Suite",
    "description": "Suite local para Windows 11/10 enfocada en mantenimiento, diagnóstico, reparación ligera, perfiles de energía y Windows 11 Power Boost.",
    "language": "PowerShell",
    "license": "MIT",
    "updated": "Hace 3 días",
    "category": "Windows / IT",
    "github": "https://github.com/ivan7800/Windows-Master-Suite",
    "pages": "https://ivan7800.github.io/Windows-Master-Suite/",
    "slug": "windows-master-suite",
    "icon": "⌘",
    "saga": "Formación & IT",
    "coverTone": "cyan",
    "coverTitle": "Windows Master Suite",
    "short": "Suite local para Windows 11/10 enfocada en mantenimiento, diagnóstico, reparación ligera, perfiles de energía y Windows…",
    "screenshot": "assets/screenshots/Windows-Master-Suite.svg"
  },
  {
    "name": "Atlas-Pattern-AI",
    "description": "Offline-first pattern discovery app for CSV data.",
    "language": "JavaScript",
    "license": "Other",
    "updated": "Hace 4 días",
    "category": "Datos / IA",
    "github": "https://github.com/ivan7800/Atlas-Pattern-AI",
    "pages": "https://ivan7800.github.io/Atlas-Pattern-AI/",
    "slug": "atlas-pattern-ai",
    "icon": "◇",
    "saga": "Herramientas",
    "coverTone": "noir",
    "coverTitle": "Atlas Pattern AI",
    "short": "Offline-first pattern discovery app for CSV data.",
    "screenshot": "assets/screenshots/Atlas-Pattern-AI.svg"
  },
  {
    "name": "Claude-Skills-Pack",
    "description": "Catálogo visual de Claude Skills.",
    "language": "CSS",
    "license": "MIT",
    "updated": "Hace 3 días",
    "category": "IA / Productividad",
    "github": "https://github.com/ivan7800/Claude-Skills-Pack",
    "pages": "https://ivan7800.github.io/Claude-Skills-Pack/",
    "slug": "claude-skills-pack",
    "icon": "◇",
    "saga": "Herramientas",
    "coverTone": "violet",
    "coverTitle": "Claude Skills Pack",
    "short": "Catálogo visual de Claude Skills.",
    "screenshot": "assets/screenshots/Claude-Skills-Pack.svg"
  },
  {
    "name": "QR-Studio-Offline",
    "description": "Aplicación local, profesional y offline-first para generar códigos QR sin enviar datos a internet.",
    "language": "JavaScript",
    "license": "MIT",
    "updated": "Hace 4 días",
    "category": "Utilidad / Privacidad",
    "github": "https://github.com/ivan7800/QR-Studio-Offline",
    "pages": "https://ivan7800.github.io/QR-Studio-Offline/",
    "slug": "qr-studio-offline",
    "icon": "◆",
    "saga": "Herramientas",
    "coverTone": "noir",
    "coverTitle": "QR Studio Offline",
    "short": "Aplicación local, profesional y offline-first para generar códigos QR sin enviar datos a internet.",
    "screenshot": "assets/screenshots/QR-Studio-Offline.svg"
  },
  {
    "name": "UI-Skills-Navigator-Pro",
    "description": "PWA offline para elegir la skill de diseño-engineering correcta antes de modificar una interfaz.",
    "language": "JavaScript",
    "license": "MIT",
    "updated": "Hace 3 días",
    "category": "Diseño / Dev",
    "github": "https://github.com/ivan7800/UI-Skills-Navigator-Pro",
    "pages": "https://ivan7800.github.io/UI-Skills-Navigator-Pro/",
    "slug": "ui-skills-navigator-pro",
    "icon": "{ }",
    "saga": "Herramientas",
    "coverTone": "cosmic",
    "coverTitle": "UI Skills Navigator Pro",
    "short": "PWA offline para elegir la skill de diseño-engineering correcta antes de modificar una interfaz.",
    "screenshot": "assets/screenshots/UI-Skills-Navigator-Pro.svg"
  },
  {
    "name": "zerokey-ai",
    "description": "Free Multi-Model AI Orchestrator.",
    "language": "HTML",
    "license": "MIT",
    "updated": "Hace 3 días",
    "category": "IA / Productividad",
    "github": "https://github.com/ivan7800/zerokey-ai",
    "pages": "https://ivan7800.github.io/zerokey-ai/",
    "slug": "zerokey-ai",
    "icon": "◇",
    "saga": "Herramientas",
    "coverTone": "noir",
    "coverTitle": "zerokey ai",
    "short": "Free Multi-Model AI Orchestrator.",
    "screenshot": "assets/screenshots/zerokey-ai.svg"
  },
  {
    "name": "doppelganger-chat",
    "description": "Chat experimental Doppelganger.",
    "language": "JavaScript",
    "license": "Sin especificar",
    "updated": "Hace 3 días",
    "category": "IA / Experimentos",
    "github": "https://github.com/ivan7800/doppelganger-chat",
    "pages": "https://ivan7800.github.io/doppelganger-chat/",
    "slug": "doppelganger-chat",
    "icon": "◇",
    "saga": "Laboratorio 404",
    "coverTone": "paper",
    "coverTitle": "doppelganger chat",
    "short": "Chat experimental Doppelganger.",
    "screenshot": "assets/screenshots/doppelganger-chat.svg"
  },
  {
    "name": "i.roig",
    "description": "Web personal de I. Roig.",
    "language": "CSS",
    "license": "Sin especificar",
    "updated": "Hace 2 días",
    "category": "Marca personal",
    "github": "https://github.com/ivan7800/i.roig",
    "pages": "https://ivan7800.github.io/i.roig/",
    "slug": "i.roig",
    "icon": "◆",
    "saga": "Laboratorio 404",
    "coverTone": "signal",
    "coverTitle": "i.roig",
    "short": "Web personal de I. Roig.",
    "screenshot": "assets/screenshots/i.roig.svg"
  },
  {
    "name": "Baraja-del-Fin",
    "description": "App web de cartas narrativas y destino oscuro, pensada como experiencia interactiva dentro del universo 404.",
    "language": "JavaScript",
    "license": "Other",
    "updated": "Nueva",
    "category": "Juegos / Horror",
    "github": "https://github.com/ivan7800/Baraja-del-Fin",
    "pages": "https://ivan7800.github.io/Baraja-del-Fin/",
    "slug": "baraja-del-fin",
    "icon": "☾",
    "saga": "Universo 404",
    "coverTone": "violet",
    "coverTitle": "Baraja del Fin",
    "short": "App web de cartas narrativas y destino oscuro dentro del universo 404.",
    "screenshot": "assets/screenshots/Baraja-del-Fin.svg"
  },
  {
    "name": "El-Criterio-Omega",
    "description": "Experiencia interactiva cinematográfica inspirada en la novela El Criterio Omega, de I. Roig.",
    "language": "HTML",
    "license": "Other",
    "updated": "Hace 1 hora",
    "category": "Narrativa / Universo 404",
    "github": "https://github.com/ivan7800/El-Criterio-Omega",
    "pages": "https://ivan7800.github.io/El-Criterio-Omega/",
    "slug": "el-criterio-omega",
    "icon": "Ω",
    "saga": "Universo 404",
    "coverTone": "signal",
    "coverTitle": "El Criterio Omega",
    "short": "Experiencia interactiva cinematográfica inspirada en la novela El Criterio Omega, de I. Roig.",
    "screenshot": "assets/screenshots/El-Criterio-Omega.svg"
  },
  {
    "name": "El-Evangelio-del-Nombre-Devorado",
    "description": "El manuscrito prohibido.",
    "language": "JavaScript",
    "license": "Other",
    "updated": "Hace 3 días",
    "category": "Narrativa / Universo 404",
    "github": "https://github.com/ivan7800/El-Evangelio-del-Nombre-Devorado",
    "pages": "https://ivan7800.github.io/El-Evangelio-del-Nombre-Devorado/",
    "slug": "el-evangelio-del-nombre-devorado",
    "icon": "Ω",
    "saga": "Universo 404",
    "coverTone": "cyan",
    "coverTitle": "El Evangelio del Nombre Devorado",
    "short": "El manuscrito prohibido.",
    "screenshot": "assets/screenshots/El-Evangelio-del-Nombre-Devorado.svg"
  },
  {
    "name": "Investigador-404",
    "description": "Aventura retro de investigación y horror cósmico para un jugador, hecha en HTML, CSS y JavaScript puro.",
    "language": "JavaScript",
    "license": "MIT",
    "updated": "Hace 3 días",
    "category": "Juegos / Horror",
    "github": "https://github.com/ivan7800/Investigador-404",
    "pages": "https://ivan7800.github.io/Investigador-404/",
    "slug": "investigador-404",
    "icon": "Ω",
    "saga": "Universo 404",
    "coverTone": "signal",
    "coverTitle": "Investigador 404",
    "short": "Aventura retro de investigación y horror cósmico para un jugador, hecha en HTML, CSS y JavaScript puro.",
    "screenshot": "assets/screenshots/Investigador-404.svg"
  },
  {
    "name": "NECRONOMICON-404",
    "description": "Grimorio interactivo de horror cósmico.",
    "language": "JavaScript",
    "license": "Other",
    "updated": "Hace 3 días",
    "category": "Narrativa / Horror",
    "github": "https://github.com/ivan7800/NECRONOMICON-404",
    "pages": "https://ivan7800.github.io/NECRONOMICON-404/",
    "slug": "necronomicon-404",
    "icon": "Ω",
    "saga": "Universo 404",
    "coverTone": "cosmic",
    "coverTitle": "NECRONOMICON 404",
    "short": "Grimorio interactivo de horror cósmico.",
    "screenshot": "assets/screenshots/NECRONOMICON-404.svg"
  },
  {
    "name": "Strategy-Lab-Campaign",
    "description": "App web interactiva para analizar decisiones, practicar escenarios, guardar planes y entrenar criterio estratégico.",
    "language": "JavaScript",
    "license": "Other",
    "updated": "Hace 3 horas",
    "category": "Estrategia / Formación",
    "github": "https://github.com/ivan7800/Strategy-Lab-Campaign",
    "pages": "https://ivan7800.github.io/Strategy-Lab-Campaign/",
    "slug": "strategy-lab-campaign",
    "icon": "◇",
    "saga": "Universo 404",
    "coverTone": "paper",
    "coverTitle": "Strategy Lab Campaign",
    "short": "App web interactiva para analizar decisiones, practicar escenarios, guardar planes y entrenar criterio estratégico.",
    "screenshot": "assets/screenshots/Strategy-Lab-Campaign.svg"
  },
  {
    "name": "Vigilia-Abisal",
    "description": "Edición con 20 expedientes jugables como homenaje original a relatos clave del universo lovecraftiano.",
    "language": "JavaScript",
    "license": "MIT",
    "updated": "Hace 3 días",
    "category": "Juegos / Horror",
    "github": "https://github.com/ivan7800/Vigilia-Abisal",
    "pages": "https://ivan7800.github.io/Vigilia-Abisal/",
    "slug": "vigilia-abisal",
    "icon": "Ω",
    "saga": "Universo 404",
    "coverTone": "paper",
    "coverTitle": "Vigilia Abisal",
    "short": "Edición con 20 expedientes jugables como homenaje original a relatos clave del universo lovecraftiano.",
    "screenshot": "assets/screenshots/Vigilia-Abisal.svg"
  },
  {
    "name": "VOX-MORPHER-404",
    "description": "Aplicación de diseño sonoro para horror, relatos y vídeo.",
    "language": "HTML",
    "license": "Sin especificar",
    "updated": "Hace 3 días",
    "category": "Música / Horror",
    "github": "https://github.com/ivan7800/VOX-MORPHER-404",
    "pages": "https://ivan7800.github.io/VOX-MORPHER-404/",
    "slug": "vox-morpher-404",
    "icon": "Ω",
    "saga": "Universo 404",
    "coverTone": "cosmic",
    "coverTitle": "VOX MORPHER 404",
    "short": "Aplicación de diseño sonoro para horror, relatos y vídeo.",
    "screenshot": "assets/screenshots/VOX-MORPHER-404.svg"
  },
  {
    "name": "calma-mental",
    "description": "App para calmar la ansiedad.",
    "language": "HTML",
    "license": "MIT",
    "updated": "Hace 3 días",
    "category": "Bienestar / Vida",
    "github": "https://github.com/ivan7800/calma-mental",
    "pages": "https://ivan7800.github.io/calma-mental/",
    "slug": "calma-mental",
    "icon": "●",
    "saga": "Vida privada",
    "coverTone": "cosmic",
    "coverTitle": "calma mental",
    "short": "App para calmar la ansiedad.",
    "screenshot": "assets/screenshots/calma-mental.svg"
  },
  {
    "name": "Guardian-Senior-AI",
    "description": "PWA local para ayudar a personas mayores a pedir ayuda rápidamente desde un móvil, con privacidad y seguridad por diseño.",
    "language": "JavaScript",
    "license": "Other",
    "updated": "Hace 3 días",
    "category": "Seguridad / Vida",
    "github": "https://github.com/ivan7800/Guardian-Senior-AI",
    "pages": "https://ivan7800.github.io/Guardian-Senior-AI/",
    "slug": "guardian-senior-ai",
    "icon": "●",
    "saga": "Vida privada",
    "coverTone": "signal",
    "coverTitle": "Guardian Senior AI",
    "short": "PWA local para ayudar a personas mayores a pedir ayuda rápidamente desde un móvil, con privacidad y seguridad por diseño…",
    "screenshot": "assets/screenshots/Guardian-Senior-AI.svg"
  },
  {
    "name": "La-Caja-Infinita",
    "description": "Experiencia web interactiva de misterio, archivo imposible y exploración narrativa dentro del ecosistema 404.",
    "language": "JavaScript",
    "license": "Other",
    "updated": "Nueva",
    "category": "Ficción interactiva",
    "github": "https://github.com/ivan7800/La-Caja-Infinita",
    "pages": "https://ivan7800.github.io/La-Caja-Infinita/",
    "slug": "la-caja-infinita",
    "icon": "▣",
    "saga": "Universo 404",
    "coverTone": "abyss",
    "coverTitle": "La Caja Infinita",
    "short": "Caja imposible, misterio interactivo y exploración narrativa del archivo 404.",
    "screenshot": "assets/screenshots/La-Caja-Infinita.svg"
  },
  {
    "name": "Web-Architect",
    "description": "Crea modelos pro de webs en segundos.",
    "language": "JavaScript",
    "license": "Other",
    "updated": "Nueva",
    "category": "Dev / Diseño",
    "github": "https://github.com/ivan7800/Web-Architect",
    "pages": "https://ivan7800.github.io/Web-Architect/",
    "slug": "web-architect",
    "icon": "⬡",
    "saga": "Herramientas",
    "coverTone": "cyan",
    "coverTitle": "Web Architect",
    "short": "Crea modelos pro de webs en segundos.",
    "screenshot": "assets/screenshots/Web-Architect.svg"
  }
];
